### ISSUE TITLE
Implement ArcGen

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/sector-file-compiler#132]
We currently have the arcgen tool. Wouldn't it be cool if we could introduce some new compiler syntax that generates them on the fly?

**Comment by AliceFord** [comment]
@AndyTWF if you could link me the ArcGen program as it is now, maybe I could have a crack at this. I think it'll make arcs a lot more obvious and easy to work with in the sector file.

**Comment by AliceFord** [comment]
Nevermind, found it at https://sectorfile.vatsim.uk/tools/arc_gen.php. I'll have a go at it!
