### ISSUE TITLE
Add line breaks for readability

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/sector-file-compiler#163]
When editing the .ese especially (but also to some extent the .sct) it's really useful to have blank lines between each 'section' of content - it makes it much more readable when making changes

Can we add these in please?

e.g. This isn't very readable as to where each sector section is:

![image](https://user-images.githubusercontent.com/12017284/136786284-ff16c58c-7989-4456-aaa4-52bfd0291dda.png)

**Comment by AndyTWF** [comment]
I'll look at a command line option for pretty printing :)
