### ISSUE TITLE
'No usable version of libssl was found' Ubuntu 22.04.1 WSL

### ISSUE THREAD

**Issue by GeekPro101** [VATSIM-UK/sector-file-compiler#191]
Installed libssl-dev and the error kept occurring

https://stackoverflow.com/questions/72108697/when-i-open-unity-and-make-something-project-then-the-error-is-coming-that-no

Followed the 'For Ubuntu' answer and it worked
Unsure if this is a problem for the compiler but did decide to pop this here to help anyone with the same issue

**Comment by AndyTWF** [comment]
Hi @GeekPro101 

Can you confirm where this occurred, was it on the UKSF actions build?

**Comment by GeekPro101** [comment]
@AndyTWF this was on a Ubuntu 22.04.1 WSL instance running on my PC, not the repo actions

**Comment by GunnyDev** [comment]
This is because Ubuntu 22.04.1 now only includes OpenSSL 3.0.2.
.Net 5 only dynamically loads OpenSSL 1.0 & 1.1.

.Net 6 and .Net 7 support OpenSSL 3. So the workaround when using Unbuntu 22.04.1 until the code base is migrated to a newer version, is to install  OpenSSL 1.0 or 1.1 as per your link.

**Comment by AndyTWF** [comment]
Hi @GeekPro101 - sorry for the delay on this, a new version of the compiler supporting .net 6 should be on its way out now, can you confirm if that fixes the issue?

**Comment by GeekPro101** [comment]
> Hi @GeekPro101 - sorry for the delay on this, a new version of the compiler supporting .net 6 should be on its way out now, can you confirm if that fixes the issue?

@AndyTWF just tested now on a fresh WSL Ubuntu 22.04.2 LTS, all working 😄

**Comment by AndyTWF** [comment]
Fantastic!
